# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"drift_welcome": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://rflizgit.github.io/drift_tests/"

git_url = "https://github.com/rflizgit/drift_tests/tree/master/"

def custom_doc_links(name): return None
