# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['drift_welcome']

# Cell
def drift_welcome(name="a mysterious user"):
    '''
    This functiontakes a name (string) and returns a personalized greeting!
    '''
    return f"Drift says 'Hello!' to {name}"
